name: Curated Job Links Workflow

on:
  workflow_dispatch: {}  # Allows manual trigger
  schedule:
    - cron: "0 9 * * *"  # Run every morning at 9 AM UTC

jobs:
  curate-and-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y jq

      - name: Curate job links
        env:
          JOB_BOARDS: "jobs.ashbyhq.com, boards.greenhouse.io, lever.co, bamboohr.com"
          MAX_LINKS: 50
        run: |
          job_links=""

          IFS=',' read -r -a job_boards <<< "$JOB_BOARDS"
          for board in "${job_boards[@]}"; do
            recent_jobs=$(curl -s "https://$board/search?query=software+engineer+OR+new+grad" | jq -r '.results[] | .href')

            if [ $? -ne 0 ]; then
              echo "::warning::Failed to fetch job links from board: $board"
            elif [ -z "$recent_jobs" ]; then
              echo "::notice::No recent job links found on board: $board"
            else
              for job in $recent_jobs; do
                job_links+="${job}\n"
              done
            fi
          done

          # Write the job links to a text file
          echo -e "${job_links}" > daily-job-links.txt
        shell: bash
        
      - name: Commit and push the text file
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add daily-job-links.txt
          git commit -m "Update daily job links"
          git push

      - name: Create GitHub issue for notification
        uses: peter-evans/create-issue-from-file@v3
        with:
          title: "Curated Job Links for $(date '+%Y-%m-%d')"
          content-filepath: daily-job-links.txt
          labels: "curated-job-links"
