name: Curated Job Links Workflow

on:
  workflow_dispatch: {}  # Enables manual trigger
  schedule:
    - cron: "0 9 * * *"  # Run every morning at 9 AM UTC

jobs:
  send-curated-job-links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Curate job links
        env:
          JOB_BOARDS: "jobs.ashbyhq.com, boards.greenhouse.io, lever.co, bamboohr.com"
          MAX_LINKS: 50
        run: |
          job_links=""

          for board in ${JOB_BOARDS//,/ }; do
            recent_jobs=$(curl -s "https://$board/search?query=software+engineer+OR+new+grad" | grep -oE 'href=[\"].+[\".]' | sed 's/href=[\""]//' | sort -n | tail -${MAX_LINKS})

            if [ $? -ne 0 ]; then
              echo "::warning::Failed to fetch job links from board: $board"
            elif [ -z "$recent_jobs" ]; then
              echo "::notice::No recent job links found on board: $board"
            else
              for job in $recent_jobs; do
                job_links+="${job}\n"
              done
            fi
          done

          echo "job_links=${job_links}" >> $GITHUB_ENV

      - name: Send trigger email
        uses: dawidd6/action-send-mail@v3
        with:
          from: "sameer.sam.more@gmail.com"
          to: "zutshi.k@northeastern.edu"
          subject: "Curated Job Links"
          body: |
            Hi!

            Here are the curated job links for you:

            ${{ env.job_links }}

            Best regards,
            Your Workflow
